Add pre-fill for the command handler tests
Becklyn/ddd-generator-bundle pull request #22
Opened 2021-10-14 13:03 UTC by oechsler

2021-10-14 13:04 UTC, oechsler commented
Do we need translation stuff here?

2021-10-14 13:38 UTC, msvujnovic-becklyn commented
Yep, I noted all the places I could see which need translation. Some of the parts which need translation already have it implemented, others you will need to create.

2021-10-14 13:38 UTC, msvujnovic-becklyn requested changes

2021-10-14 13:38 UTC, msvujnovic-becklyn commented on src/Resources/skeleton/ddd/command-handler-test.tpl.php
> +    public function test_TESTED_LOGIC_Is_ACTIONED_And<?= $entity; ?>IsDequeuedByEventRegistry() : void
`_TESTED_LOGIC_Is_ACTIONED_` -> `_TESTED_LOGIC_IS_ACTIONED_`

Translation for 'And' & 'IsDequeuedByEventRegisty' is needed

2021-10-14 13:38 UTC, msvujnovic-becklyn commented on src/Resources/skeleton/ddd/command-handler-test.tpl.php
> +        $<?= $strtocamel($entity); ?> = $this->given<?= $entity; ?>CanBeFoundById($<?= $strtocamel($entity); ?>Id);
Translation for 'given' and 'CanBeFoundById' is needed

2021-10-14 13:38 UTC, msvujnovic-becklyn commented on src/Resources/skeleton/ddd/command-handler-test.tpl.php
> +        $this->then_SOMETHING_ShouldBe_ACTIONED_($<?= $strtocamel($entity); ?> /** TODO additional params **/);
Translation for 'then' and 'ShouldBe' is needed

2021-10-14 13:38 UTC, msvujnovic-becklyn commented on src/Resources/skeleton/ddd/command-handler-test.tpl.php
> +        $this->then<?= $entity; ?>ShouldBeDequeuedByEventRegistry($<?= $strtocamel($entity); ?>->reveal());
Translation for 'then' and 'ShouldBeDequeuedByEventRegistry' is needed

2021-10-14 13:38 UTC, msvujnovic-becklyn commented on src/Resources/skeleton/ddd/command-handler-test.tpl.php
> +        $this->when<?= $extra["command_namespace"]; ?>IsHandled($<?= $strtocamel($entity); ?>Id /** TODO additional command params **/);
Translation for 'when' and 'IsHandled' is needed

2021-10-14 13:38 UTC, msvujnovic-becklyn commented on src/Resources/skeleton/ddd/command-handler-test.tpl.php
> +    private function then_SOMETHING_ShouldBe_ACTIONED_(ObjectProphecy | <?= $entity; ?> $<?= $strtocamel($entity); ?> /** TODO additional params **/) : void
Translation for 'then' and 'ShouldBeDequeuedByEventRegistry' is needed

2021-10-14 13:38 UTC, msvujnovic-becklyn commented on src/Resources/skeleton/ddd/command-handler-test.tpl.php
> +    private function when<?= $extra["command_namespace"]; ?>IsHandled(<?= $entity; ?>Id $<?= $strtocamel($entity); ?>Id /** TODO additional command params **/) : void
Translation for 'when' and 'IsHandled' is needed

2021-10-14 13:38 UTC, msvujnovic-becklyn commented on src/Resources/skeleton/ddd/entity-test-trait.tpl.php
> +    protected function then<?= $entity; ?>ShouldBeDequeuedByEventRegistry($<?= $strtocamel($entity); ?>) : void
Translation for 'then' and 'ShouldBeDequeuedByEventRegistry' is needed

2021-10-14 14:39 UTC, glassp approved these changes
Should be good after the changes Marko requested

2021-10-15 09:11 UTC, msvujnovic-becklyn requested changes

2021-10-15 09:11 UTC, msvujnovic-becklyn commented on src/Resources/i18n/de.yaml
> +    dequeued_by_event_registry: VonDerEventRegisitrierungAusDerWarteschlangeEntfernt
Bwah :D

Machma lieber `VonDerEventRegistryDequeued`, weil die event registry ist da auf Englich in der Codebasis, und wir benutzen auch Englische begriffe wenn wir drüber reden.

2021-10-15 09:13 UTC, oechsler commented on src/Resources/i18n/de.yaml
> +    dequeued_by_event_registry: VonDerEventRegisitrierungAusDerWarteschlangeEntfernt
Ok, kann auch nix dafür, dass Deutsch dreck is 🤣

2021-10-15 09:52 UTC, msvujnovic-becklyn approved these changes

2021-10-15 09:53 UTC, merged