[2.x] Use symfony/process and fix CS
Becklyn/ddd-generator-bundle pull request #9
Opened 2021-08-26 11:11 UTC by glassp

2021-08-26 11:13 UTC, glassp commented
This is basically the same as #8 but adjusted for PHP 8

2021-08-26 15:50 UTC, keichinger commented on vendor-bin/test/.php_cs.custom.php
> +<?php declare(strict_types=1);
This file can be placed in the root directory of the bundle, next to all other dot-files :)

2021-08-26 15:53 UTC, keichinger commented on src/Helper/GitUserInfoFetcher.php
> +        $composerFileContents = \json_decode(\file_get_contents($composerFile), true, 521, \JSON_THROW_ON_ERROR);
Having that `\JSON_THROW_ON_ERROR` flag usually comes with a `try {} catch (…) {}` to properly handle it. Right now, your command would just crash in an exception. While this may usually be fine, having a human readable error that tells you exactly what's going on (ideally nicely formatted) is the far better developer experience ☺️

2021-08-26 15:55 UTC, keichinger requested changes
Only a few minor details (which I've commented as inline comment - sorry!) but then we're good to go! :)

2021-08-30 11:10 UTC, keichinger approved these changes

2021-08-30 11:11 UTC, merged